/**
 * The sat_parameters file provide the basic satellites information include
 *        prn, svn, launched time, decommissioned time, weight of sat and so on.
 *
 * Following is an example for the header sat_parameters file.
 *
 * @verbatim
        ## Satelite Parameters, Generated by atx2sat, run by fzhou, 17-Nov-16
        #                                          LAUNCHED      DECOMMISSIONED           MASS   MAX_YAW                
        #PRN                  SVN                  YYYYDDD:SSSSS YYYYDDD:SSSSS COSPAR-ID  [KG]   [DEG]    FID BLOCK-TYPE
        #---------------------------------------------------------------------------------------------------------------
   @endverbatim
 *
 * Following is an example for the body of sat_parameters file.
 *
 * @verbatim
        =============================================================================================
        +prn_indexed        ! Mark for begin of prn record
        ================================================================================================================
       ! Prn                  svn                   launched time retired time  cospar-id  mass(kg) max_yaw fid  block-type
        ================================================================================================================
         C01                  G049                 2009083:00000 0000000:00000 2009-014A  1100.00   0.121   0 BEIDOU-2G
         C01                  C003                 2010016:00000 0000000:00000 2010-001A  1550.00   0.000   0 BEIDOU-2G

        -prn_indexed        ! Mark for end of prn record

        #SVN                  PRN                  YYYYDDD:SSSSS YYYYDDD:SSSSS COSPAR-ID  [KG]   [DEG]    FID BLOCK-TYPE
        +svn_indexed        ! Mark for begin of svn record
         C001                 C30                  2007103:00000 0000000:00000 2007-011A  1415.00   0.000   0 BEIDOU-2M
         C003                 C01                  2010016:00000 0000000:00000 2010-001A  1550.00   0.000   0 BEIDOU-2G
        -svn_indexed        ! Mark for end of svn record
   @endverbatim
 *
 * @file        satparameters.h
 * @brief        decode sat_parameters file data.
 *
 */

#ifndef hwa_gnss_coder_satparam_H
#define hwa_gnss_coder_satparam_H

#include "hwa_gnss_coder_BASE.h"
#include "hwa_gnss_all_Satparam.h" //glfeng

using namespace hwa_base;

namespace hwa_gnss
{
    /**
    *@brief       Class for decoding sat_parameters file data
    * 
    * The file contains the basic satellites information include prn,
    *        svn, launched time, decommissioned time, weight of sat, 
    *        frequency-id and block type.
    * The gcoder gnss_coder_satparam corresponding to the gdata satparam and gallsatparm.
    */
    class gnss_coder_satparam : public gnss_base_coder
    {
    public:
        /**
         * @brief default constructor.
         *
         * @param[in]  s        setbase control
         * @param[in]  version  version of the gcoder
         * @param[in]  sz       size of the buffer
         */
        explicit gnss_coder_satparam(set_base *s, std::string version = "", int sz = DEFAULT_BUFFER_SIZE);

        /** @brief defult destructor. */
        virtual ~gnss_coder_satparam();

        /**
        * @brief decode header of sat_parameters_new file
        * @param[in]  buff        buffer of the data
        * @param[in]  sz          buffer size of the data
        * @param[in]  errmsg      error message of the data decoding
        * @return 
            @retval >=0 consume size of header decoding
            @retval <0  finish reading
        */
        virtual int decode_head(char *buff, int sz, std::vector<std::string> &errmsg);

        /**
        * @brief decode data body of sat_parameters_new file
        * @param[in]  buff        buffer of the data
        * @param[in]  sz          buffer size of the data
        * @param[in]  errmsg      error message of the data decoding
        * @return 
            @retval >=0 consume size of body decoding
            @retval <0  finish reading
        */
        virtual int decode_data(char *buff, int sz, int &cnt, std::vector<std::string> &errmsg);

    protected:
    private:
        int _flag; ///<flag for data type (=1:+prn_indexed;=2:+svn_indexed)
        /**
        * @brief day of year to month and day
        * @param[in]   year        year
        * @param[in]   doy         day of year
        * @param[out]  month       month
        * @param[out]  day           day
        */
        void yeardoy2monthday(int year, int doy, int *month, int *day);
    };
}
#endif // !SAT_PARAMETERS_H
